service: pre-paid-cards

plugins:
  - serverless-auto-swagger
  - serverless-middleware
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # middleware:
  #   pre:
  #     - src/common/middlewares/function-role-middleware.check
  autoswagger:
    typefiles: ['./src/types/api-types.d.ts']
    generateSwaggerOnDeploy: true
    basePath: '/doc'
    host: 'http://0.0.0.0:3000'
    schemes: ['http', 'https', 'ws', 'wss']
    excludeStages: ['production', 'anyOtherStage']

functions:
  create-category:
    handler: dist/category/handlers.create
    events:
      - http:
          method: POST
          path: /category
  find-all-category:
    handler: dist/category/handlers.findAll
    events:
      - http:
          method: GET
          path: /category