service: pre-paid-cards

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  create-category:
    handler: dist/category/handlers.create
    events:
      - http:
          method: POST
          path: /category
  find-all-category:
    handler: dist/category/handlers.findAll
    events:
      - http:
          method: GET
          path: /category